CREATE TABLE IF NOT EXISTS users (
    user_id CHAR(36) PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    username VARCHAR(100) NOT NULL UNIQUE,
    is_admin BOOL DEFAULT FALSE NOT NULL,
    is_active BOOL DEFAULT TRUE NOT NULL,
    register_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
